title:              Michael's Blog
email:              mikeykim1338@gmail.com
description:        My Blog for Exploring Real Estate Topics
author:             Michael Kim
baseurl:            ""
url:                "https://michaelkimy.github.io"
theme:              jekyll-theme-clean-blog

# Social Profiles
twitter_username:   mkim1338
github_username:    michaelkimy
facebook_username:  
instagram_username:  
linkedin_username:  michaelkimy

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
